name: Lint

on:
    pull_request:
        types: [opened, reopened]
        branches: [develop, staging, master]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: psf/black@stable
              with:
                options: "--check --verbose"