name: Test

on:
  workflow_dispatch:
  push:
    branches:
      [develop, staging, master]
  pull_request:
    branches:
      [develop, staging, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python (with pip cache)
        uses: actions/setup-python@v5
        with:
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Pytest
        run: pytest
      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}