name: Test

on:
    pull_request:
        branches:
            [develop, staging, master]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                cache: 'pip' # caching pip dependencies
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Test with pytest
              run: pytest